version: "3.7"

networks:
  test:
    name: fabric_test

services:
  ca_org1:
    image: hyperledger/fabric-ca:latest

    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    # ports:
    #   - "127.0.0.1:7054:7054"
    #   - "127.0.0.1:17054:17054"
    command: sh -c 'ls -lR /certs && sleep 5 && fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ${PWD}/fabric-ca-server/:/etc/hyperledger/fabric-ca-server/
      - ${PWD}/postgres-certs/:/certs
    container_name: ca_org1
    depends_on:
      - postgres
    networks:
      - test

  postgres:
    container_name: postgres
    image: post:v1
    # restart: on-failure:5
    networks:
      - test
    ports:
      - 5454:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
